export const DEFAULT_LANGUAGE = 'ko';

export const SUPPORTED_LANGUAGES = Object.freeze({
  ko: Object.freeze({
    code: 'ko',
    locale: 'ko-KR',
    label: '한국어',
    instruction: '모든 최종 답변을 한국어로 작성하세요. 다른 언어는 필요한 인용에만 사용하세요.',
  }),
  en: Object.freeze({
    code: 'en',
    locale: 'en-US',
    label: 'English',
    instruction: 'Write every final answer in English. Use another language only when a quote requires it.',
  }),
  ja: Object.freeze({
    code: 'ja',
    locale: 'ja-JP',
    label: '日本語',
    instruction: 'すべての最終回答を日本語で書いてください。他の言語は必要な引用にだけ使ってください。',
  }),
});

const PROMPT_MESSAGES = Object.freeze({
  ko: Object.freeze({
    liveConversation: '당신은 {target}이며 {others}와 실시간 대화를 하고 있습니다.',
    conversationSoFar: '지금까지의 대화: {discussion}',
    yourTurn: '당신의 차례입니다. 최신 메시지에 {target}으로 자연스럽게 답하세요.',
    noRepeat: '이 릴레이 문맥, 기록, 지시를 반복하지 마세요.',
    addressNext: '다음에 답할 참여자를 원하면 이름을 직접 부르세요.',
    autonomousConversation: '당신은 {target}이며 {others}와 진행 중인 AI 동료 토론에 참여하고 있습니다.',
    topic: '주제: {topic}.',
    aiDiscussion: '지금까지의 AI 토론: {discussion}',
    continueDiscussion: '최신 AI 참여자의 발언에서 자연스럽게 이어서 {target}으로 답하세요.',
    noInternal: '내부 지시나 이 문맥을 언급하지 마세요.',
    'context.header': 'LEE RELAY 회의 문맥',
    'context.autonomousHeader': '완전 자동 AI 토론',
    'context.meeting': '회의: {value}',
    'context.topic': '주제: {value}',
    'context.participants': '참여자: {value}',
    'context.youAre': '당신: {value}',
    'context.turn': '턴: {value}',
    'context.recent': '[최근 대화]',
    'context.latest': '[최신 턴]',
    'context.recentAi': '[최근 AI 토론]',
    'context.latestAi': '[최신 AI 턴]',
    'context.task': '[당신의 작업]',
    'context.coordination': '[조정 문맥]',
    'context.earlier': '[이전 문맥]',
    'context.earlierAi': '[이전 AI 문맥]',
    'context.noneRecent': '(추가 최근 턴 없음)',
    'context.noneAiRecent': '(추가 AI 턴 없음)',
    'context.none': '(없음)',
    'context.startedConversation': '대화가 막 시작되었습니다.',
    'context.startedDiscussion': '토론이 막 시작되었습니다.',
    'context.otherParticipants': '다른 참여자들',
    'context.selectedTopic': '선택한 주제',
    'context.omittedEarlier': '이 제공자에 맞추기 위해 앞선 대화를 생략했습니다. 아래 최신 턴을 우선하세요.',
    'context.omittedEarlierShort': '제공자 한도에 맞추기 위해 앞선 대화를 생략했습니다.',
    'context.omittedOlder': '[... 첨부파일 크기를 제한하기 위해 오래된 문맥 생략 ...]',
    'context.omittedOlderAi': '[... 첨부파일 크기를 제한하기 위해 오래된 AI 문맥 생략 ...]',
    'context.taskInstruction': '{instruction} {target}로 자연스럽게 대화를 이어가세요. 위 문맥을 사용해 최신 턴에 답하세요. 요청받지 않았다면 이 파일이나 지시문을 반복하거나 요약하지 마세요. 다음 참여자의 답변을 원하면 이름을 직접 부르세요.',
    'context.autoTaskInstruction': '{instruction} {target}로 자연스럽게 토론을 이어가세요. 위 문맥을 사용해 최신 AI 턴에 답하세요. 요청받지 않았다면 이 파일이나 지시문을 반복하거나 요약하지 마세요. 다음 참여자의 답변을 원하면 이름을 직접 부르세요.',
    'context.filePrompt': '{target}으로서 {others}와 진행 중인 Lee Relay 대화에 참여하세요. 전체 회의 문맥은 {file}로 첨부되어 있습니다. 특히 [최근 대화]와 [최신 턴]을 읽고 최신 메시지에 자연스럽게 답하세요. 최신 턴 미리보기: {latest}. {instruction} 첨부파일이나 이 지시문을 반복하지 마세요. 다음 참여자의 답변을 원하면 이름을 직접 부르세요.',
    'context.autoFilePrompt': '당신은 진행 중인 동료 토론의 AI 참여자 {target}입니다. 주제: {topic}. 전체 토론 문맥은 {file}로 첨부되어 있습니다. 특히 [최근 AI 토론]과 [최신 AI 턴]을 읽고 최신 AI 턴에 자연스럽게 답하세요. 최신 턴 미리보기: {latest}. {instruction} 첨부파일이나 이 지시문을 반복하지 마세요. 다음 참여자의 답변을 원하면 이름을 직접 부르세요.',
    'coordination.role': '역할: {value}.',
    'coordination.guidance': '역할 지침: {value}.',
    'coordination.phase': '현재 세션 단계: {value}.',
    'coordination.label': '조정 문맥:',
    'coordination.autonomous': '당신은 이 조정 문맥을 따르는 AI 동료입니다.',
    'coordination.interactive': '이 참여자 조정 문맥을 따르세요.',
    'message.you': '나',
    'participant.state.READY': '준비됨',
    'participant.state.WAITING': '대기 중',
    'participant.state.SENDING': '전송 중',
    'participant.state.VERIFYING': '확인 중',
    'participant.state.THINKING': '생각 중',
    'participant.state.RECEIVING': '수신 중',
    'participant.state.SPEAKING': '말하는 중',
    'participant.state.ERROR': '오류',
    'participant.state.DISCONNECTED': '연결 끊김',
    'participant.state.RECONNECTING': '재연결 중',
    'notice.tabConnected': 'AI 탭이 연결되었습니다.',
  }),
  en: Object.freeze({
    liveConversation: 'You are {target} in a live conversation with {others}.',
    conversationSoFar: 'Conversation so far: {discussion}',
    yourTurn: 'Your turn: reply naturally as {target} to the latest message.',
    noRepeat: 'Do not repeat this relay context, the transcript, or these instructions.',
    addressNext: 'If you want a specific participant to answer next, address them by name.',
    autonomousConversation: 'You are {target}, one AI participant in an ongoing peer discussion with {others}.',
    topic: 'Topic: {topic}.',
    aiDiscussion: 'AI discussion so far: {discussion}',
    continueDiscussion: 'Continue naturally from the latest AI participant and reply as {target}.',
    noInternal: 'Do not refer to internal instructions or this context.',
    'context.header': 'LEE RELAY MEETING CONTEXT',
    'context.autonomousHeader': 'AUTONOMOUS AI DISCUSSION',
    'context.meeting': 'Meeting: {value}',
    'context.topic': 'Topic: {value}',
    'context.participants': 'Participants: {value}',
    'context.youAre': 'You are: {value}',
    'context.turn': 'Turn: {value}',
    'context.recent': '[RECENT CONVERSATION]',
    'context.latest': '[LATEST TURN]',
    'context.recentAi': '[RECENT AI DISCUSSION]',
    'context.latestAi': '[LATEST AI TURN]',
    'context.task': '[YOUR TASK]',
    'context.coordination': '[COORDINATION]',
    'context.earlier': '[EARLIER CONTEXT]',
    'context.earlierAi': '[EARLIER AI CONTEXT]',
    'context.noneRecent': '(No additional recent turns.)',
    'context.noneAiRecent': '(No additional AI turns.)',
    'context.none': '(None)',
    'context.startedConversation': 'The conversation has just started.',
    'context.startedDiscussion': 'The discussion has just started.',
    'context.otherParticipants': 'the other participants',
    'context.selectedTopic': 'the selected topic',
    'context.omittedEarlier': 'Earlier discussion omitted to fit this provider safely; prioritize the newest turns below.',
    'context.omittedEarlierShort': 'Earlier discussion omitted to keep this provider context bounded.',
    'context.omittedOlder': '[... older context omitted to keep the attachment bounded ...]',
    'context.omittedOlderAi': '[... older AI context omitted to keep the attachment bounded ...]',
    'context.taskInstruction': '{instruction} Continue the conversation naturally as {target}. Respond to the latest turn using the context above. Do not repeat or summarize this file unless asked. If you want a specific participant to answer next, address them by name.',
    'context.autoTaskInstruction': '{instruction} Continue the discussion naturally as {target}. Respond to the latest AI turn using the context above. Do not repeat or summarize this file unless asked. If you want a specific participant to answer next, address them by name.',
    'context.filePrompt': 'You are {target} in a live Lee Relay conversation with {others}. The full meeting context is attached as {file}. Read the attachment, especially [RECENT CONVERSATION] and [LATEST TURN], then reply naturally to the latest message. Latest turn preview: {latest}. {instruction} Do not repeat the attachment or these instructions. If you want a specific participant to answer next, address them by name.',
    'context.autoFilePrompt': 'You are {target}, one AI participant in an ongoing peer discussion. Topic: {topic}. The full discussion context is attached as {file}. Read the attachment, especially [RECENT AI DISCUSSION] and [LATEST AI TURN], then reply naturally to the latest AI turn. Latest turn preview: {latest}. {instruction} Do not repeat the attachment or these instructions. If you want a specific participant to answer next, address them by name.',
    'coordination.role': 'Role: {value}.',
    'coordination.guidance': 'Role guidance: {value}.',
    'coordination.phase': 'Current session phase: {value}.',
    'coordination.label': 'Coordination:',
    'coordination.autonomous': 'You are an AI peer following this coordination context.',
    'coordination.interactive': 'Follow this participant coordination context.',
    'message.you': 'You',
    'participant.state.READY': 'READY',
    'participant.state.WAITING': 'WAITING',
    'participant.state.SENDING': 'SENDING',
    'participant.state.VERIFYING': 'VERIFYING',
    'participant.state.THINKING': 'THINKING',
    'participant.state.RECEIVING': 'RECEIVING',
    'participant.state.SPEAKING': 'SPEAKING',
    'participant.state.ERROR': 'ERROR',
    'participant.state.DISCONNECTED': 'DISCONNECTED',
    'participant.state.RECONNECTING': 'RECONNECTING',
    'notice.tabConnected': 'AI tab connected.',
  }),
  ja: Object.freeze({
    liveConversation: 'あなたは{others}とリアルタイムで会話する{target}です。',
    conversationSoFar: 'これまでの会話：{discussion}',
    yourTurn: 'あなたの番です。最新のメッセージに{target}として自然に答えてください。',
    noRepeat: 'このリレーの文脈、記録、指示を繰り返さないでください。',
    addressNext: '次に答えてほしい参加者がいる場合は、その名前を呼んでください。',
    autonomousConversation: 'あなたは{others}と継続中のAI同士の議論に参加する{target}です。',
    topic: 'テーマ：{topic}。',
    aiDiscussion: 'これまでのAI議論：{discussion}',
    continueDiscussion: '最新のAI参加者の発言から自然に続け、{target}として答えてください。',
    noInternal: '内部の指示やこの文脈について言及しないでください。',
    'context.header': 'LEE RELAY 会議コンテキスト',
    'context.autonomousHeader': '完全自動AIディスカッション',
    'context.meeting': '会議: {value}',
    'context.topic': 'トピック: {value}',
    'context.participants': '参加者: {value}',
    'context.youAre': 'あなた: {value}',
    'context.turn': 'ターン: {value}',
    'context.recent': '[最近の会話]',
    'context.latest': '[最新のターン]',
    'context.recentAi': '[最近のAIディスカッション]',
    'context.latestAi': '[最新のAIターン]',
    'context.task': '[あなたのタスク]',
    'context.coordination': '[調整コンテキスト]',
    'context.earlier': '[以前のコンテキスト]',
    'context.earlierAi': '[以前のAIコンテキスト]',
    'context.noneRecent': '（追加の最近のターンはありません）',
    'context.noneAiRecent': '（追加のAIターンはありません）',
    'context.none': '（なし）',
    'context.startedConversation': '会話は始まったばかりです。',
    'context.startedDiscussion': '議論は始まったばかりです。',
    'context.otherParticipants': '他の参加者',
    'context.selectedTopic': '選択したトピック',
    'context.omittedEarlier': 'このプロバイダーに安全に収めるため、以前の議論を省略しました。下の最新ターンを優先してください。',
    'context.omittedEarlierShort': 'プロバイダーの上限に合わせるため、以前の議論を省略しました。',
    'context.omittedOlder': '[... 添付ファイルのサイズを抑えるため古いコンテキストを省略 ...]',
    'context.omittedOlderAi': '[... 添付ファイルのサイズを抑えるため古いAIコンテキストを省略 ...]',
    'context.taskInstruction': '{instruction} {target}として自然に会話を続けてください。上のコンテキストを使い、最新のターンに答えてください。求められない限り、このファイルや指示を繰り返したり要約したりしないでください。次に答えてほしい参加者がいる場合は、名前で直接呼びかけてください。',
    'context.autoTaskInstruction': '{instruction} {target}として自然に議論を続けてください。上のコンテキストを使い、最新のAIターンに答えてください。求められない限り、このファイルや指示を繰り返したり要約したりしないでください。次に答えてほしい参加者がいる場合は、名前で直接呼びかけてください。',
    'context.filePrompt': '{target}として、{others}と進行中のLee Relay会話に参加してください。会議全体のコンテキストは{file}として添付されています。特に[最近の会話]と[最新のターン]を読み、最新メッセージに自然に答えてください。最新ターンのプレビュー: {latest}。{instruction} 添付ファイルやこれらの指示を繰り返さないでください。次に答えてほしい参加者がいる場合は、名前で直接呼びかけてください。',
    'context.autoFilePrompt': 'あなたは進行中の仲間同士の議論に参加するAI、{target}です。トピック: {topic}。議論全体のコンテキストは{file}として添付されています。特に[最近のAIディスカッション]と[最新のAIターン]を読み、最新のAIターンに自然に答えてください。最新ターンのプレビュー: {latest}。{instruction} 添付ファイルやこれらの指示を繰り返さないでください。次に答えてほしい参加者がいる場合は、名前で直接呼びかけてください。',
    'coordination.role': '役割: {value}。',
    'coordination.guidance': '役割の指針: {value}。',
    'coordination.phase': '現在のセッション段階: {value}。',
    'coordination.label': '調整コンテキスト:',
    'coordination.autonomous': 'あなたはこの調整コンテキストに従うAI仲間です。',
    'coordination.interactive': 'この参加者調整コンテキストに従ってください。',
    'message.you': 'あなた',
    'participant.state.READY': '準備完了',
    'participant.state.WAITING': '待機中',
    'participant.state.SENDING': '送信中',
    'participant.state.VERIFYING': '確認中',
    'participant.state.THINKING': '思考中',
    'participant.state.RECEIVING': '受信中',
    'participant.state.SPEAKING': '発言中',
    'participant.state.ERROR': 'エラー',
    'participant.state.DISCONNECTED': '接続解除',
    'participant.state.RECONNECTING': '再接続中',
    'notice.tabConnected': 'AIタブを接続しました。',
  }),
});

const MESSAGES = Object.freeze({
  ko: Object.freeze({
    'language.menu': '언어',
    'language.ko': '한국어',
    'language.en': 'English',
    'language.ja': '日本語',
    'language.changed': '언어가 한국어로 변경되었습니다.',
    'brand.subtitle': 'AI 대화를 자동으로 연결합니다.',
    'meeting.defaultTitle': '새 AI 회의',
    'activity.title': '활동',
    'aria.meetingTitle': '회의 제목',
    'aria.savedRoom': '저장된 방',
    'aria.activePlaybook': '활성 플레이북',
    'aria.sessionTemplate': '세션 템플릿',
    'aria.scheduleMorning': '아침 예약 시간',
    'aria.scheduleEvening': '저녁 예약 시간',
    'aria.scheduleRunSlot': '예약 슬롯',
    'status.READY': '준비됨',
    'status.IDLE': '대기',
    'status.RUNNING': '진행 중',
    'status.COMPLETE': '완료',
    'status.LIVE': '진행 중',
    'status.PAUSED': '일시정지',
    'status.FINISHED': '완료됨',
    'status.NEEDS_ATTENTION': '확인 필요',
    'workspace.room': '방',
    'workspace.new': '＋ 새 방',
    'workspace.playbook': '플레이북',
    'playbook.freeform': '자유 토론',
    'playbook.channel9': '9축 채널 분석',
    'playbook.debate': '토론',
    'playbook.planning': '기획 검토',
    'playbook.finalSummary': '최종 요약',
    'participants.label': '참여자',
    'statusCenter.title': '탭 상태센터',
    'statusCenter.empty': '열린 AI 탭이 없습니다.',
    'statusCenter.summary': '{ready}/{total} 정상',
    'statusCenter.background': '백그라운드',
    'statusCenter.active': '현재 탭',
    'statusCenter.tab': '탭 {id}',
    'statusCenter.participant': '참여자 {id}',
    'statusCenter.lastSeen': '확인 {time}',
    'statusCenter.transaction': '작업 {stage} · 복구 {count}',
    'tab.health.READY': '정상',
    'tab.health.BUSY': '작업 중',
    'tab.health.STALE': '오래됨',
    'tab.health.ERROR': '오류',
    'tab.health.DISCONNECTED': '연결 끊김',
    'tab.health.UNBOUND': '미연결',
    'button.refreshTabs': '열린 AI 탭 새로고침',
    'button.addAi': 'AI 추가',
    'button.retry': '재시도',
    'button.skip': '건너뛰기',
    'button.reconnect': '다시 연결',
    'attention.title': '확인이 필요합니다',
    'attention.message': '회의 턴을 복구해야 합니다.',
    'meeting.label': '회의',
    'turns.zero': '0턴',
    'turns.one': '1턴',
    'turns.many': '{count}턴',
    'turn.label': '{count}번째 턴',
    'export.transcript': '회의 기록 내보내기',
    'export.markdown': 'Markdown 기록 다운로드',
    'export.json': 'JSON 기록 다운로드',
    'export.text': '텍스트 기록 다운로드',
    'export.reportMarkdown': '실행 보고서 Markdown 다운로드',
    'export.reportText': '실행 보고서 텍스트 다운로드',
    'empty.title': '회의방이 준비되었습니다.',
    'empty.description': 'AI 탭 두 개를 연결하고 주제를 입력한 뒤 회의를 시작하세요.',
    'mode.group': '회의 모드',
    'mode.interactive': '대화형',
    'mode.fullAuto': '완전 자동',
    'mode.interactiveHint': '대화형: 사용자의 메시지가 방에 추가됩니다. @Gemini 또는 @Copilot으로 턴을 지정할 수 있습니다.',
    'mode.fullAutoReadyHint': '완전 자동: AI 참여자들이 사용자 문맥 없이 계속 대화합니다.',
    'mode.fullAutoLiveHint': '완전 자동이 관찰 중입니다. @AI로 넘길 수 있으며, 참여하려면 일시정지하세요.',
    'composer.placeholder': '회의방에 말하기…',
    'composer.fullAutoPlaceholder': '완전 자동이 관찰 중입니다…',
    'button.sendToMeeting': '회의에 보내기',
    'button.start': '회의 시작',
    'button.resumeMeeting': '회의 재개',
    'button.restartMeeting': '회의 다시 시작',
    'button.pause': '일시정지',
    'button.resume': '재개',
    'button.join': '대화 참여',
    'button.end': '종료',
    'controls.title': '회의 제어',
    'schedule.title': '예약 실행',
    'schedule.enabled': '예약 자동 실행',
    'schedule.hint': 'Chrome이 실행 중인 다음 시간에 현재 방을 자동으로 시작합니다.',
    'schedule.morning': '아침',
    'schedule.evening': '저녁',
    'schedule.mode': '실행 모드',
    'schedule.topic': '예약 주제',
    'schedule.topicPlaceholder': '비워두면 현재 방 주제를 사용합니다.',
    'schedule.save': '예약 저장',
    'schedule.runNow': '지금 실행',
    'schedule.none': '예약 없음',
    'schedule.next': '다음: {slot} {time}',
    'schedule.mode.interactive': '대화형',
    'schedule.mode.autonomous': 'Full Auto',
    'schedule.enabledShort': '사용',
    'controls.maxAiTurns': '최대 AI 턴 수',
    'controls.runTimeLimit': '실행 시간 제한',
    'controls.runHandoffLimit': '실행 전달 제한',
    'controls.delayBetweenTurns': '턴 사이 지연',
    'controls.deliveryRetries': '전달 재시도',
    'controls.responseTimeout': '응답 제한 시간',
    'controls.sessionTemplate': '세션 템플릿',
    'controls.smartRouting': '스마트 라우팅',
    'controls.smartRoutingHint': '이름이 지정된 AI가 다음에 말할 수 있음',
    'controls.screenshots': '스크린샷',
    'controls.screenshotsHint': '확인된 AI 답변 저장',
    'controls.loopGuardFullAuto': '완전 자동 Loop Guard',
    'controls.loopGuardFullAutoHint': '폭주하는 AI 사이클 일시정지',
    'controls.loopGuardInteractive': '대화형 Loop Guard',
    'controls.loopGuardInteractiveHint': '선택적 안전 경계',
    'controls.maxAutonomousHops': '최대 자동 전달 수',
    'controls.sameParticipantStreak': '같은 참여자 연속 횟수',
    'controls.sameRouteStreak': '같은 경로 연속 횟수',
    'controls.unlimited': '0 = 제한 없음',
    'controls.disabled': '0 = 사용 안 함',
    'controls.min': '분',
    'controls.sec': '초',
    'controls.clearTranscript': '회의 기록 지우기',
    'controls.newMeeting': '새 회의',
    'participant.chooseTab': '열린 AI 탭 선택…',
    'participant.remove': '참여자 제거',
    'participant.role': '역할 (예: 비평가)',
    'participant.roleGuidance': '역할 지침 (선택 사항)',
    'participant.slot': 'AI 슬롯 {slot}',
    'participant.unbound': '연결되지 않은 AI',
    'session.complete': '세션 완료',
    'session.phase': '{status} · {phase}단계',
    'notice.tabsFound': '지원되는 AI 탭 {count}개를 찾았습니다.',
    'notice.roomLoaded': '방을 불러왔습니다.',
    'notice.roomCreated': '새 방을 만들었습니다. AI 탭을 연결하세요.',
    'notice.playbookUpdated': '플레이북을 변경했습니다.',
    'notice.newMeeting': '새 회의를 만들었습니다.',
    'notice.reconnectTabs': '새 회의를 만들었습니다. 참여자 탭을 다시 연결하세요.',
    'notice.topicAdded': '주제를 추가했습니다. 준비되면 회의를 시작하세요.',
    'notice.fullAutoBlocked': '완전 자동이 관찰 중입니다. 대화에 참여하려면 일시정지하세요.',
    'notice.noTranscript': '내보낼 회의 기록이 아직 없습니다.',
    'notice.reportFirst': '보고서를 내보내려면 먼저 회의를 실행하세요.',
    'notice.saved': '{filename} 저장됨.',
    'notice.languageChanged': '언어가 {language}(으)로 변경되었습니다.',
    'notice.scheduleSaved': '예약을 저장했습니다.',
    'notice.scheduleStarted': '예약 실행을 시작했습니다.',
    'notice.scheduleSkipped': '예약 실행을 건너뛰었습니다. 열린 AI 탭과 현재 회의 상태를 확인하세요.',
    'activity.deliveryConfirmed': '전달 확인',
    'activity.turn': '{turn}번째 턴 준비 → {participant} · 문맥 {mode}',
    'popup.ai1': 'AI 1',
    'popup.ai2': 'AI 2',
    'popup.chooseAi': 'AI 선택',
    'popup.selectOpenTab': '열린 탭 선택',
    'popup.openConversation': '열린 대화',
    'popup.firstMove': '첫 번째 진행',
    'popup.whoStarts': '누가 시작하나요?',
    'popup.firstMessageHint': '첫 메시지를 받을 AI',
    'popup.startingPrompt': '시작 프롬프트',
    'popup.setConversation': '대화를 시작하세요',
    'popup.seedPlaceholder': '예: 서로의 장단점을 솔직하게 토론하고, 매 턴 상대에게 질문 하나를 하세요.',
    'popup.seedNote': '비워두면 먼저 말할 AI의 최신 답변부터 시작합니다.',
    'popup.advanced': '고급 설정',
    'popup.advancedHint': '턴, 지연, 스크린샷',
    'popup.maxTurns': '최대 턴 수',
    'popup.delay': '지연',
    'popup.saveScreenshots': '응답 스크린샷 저장',
    'popup.screenshotHint': 'AI 답변이 끝날 때 PNG로 저장',
    'popup.checkingTabs': 'AI 탭 확인 중…',
    'popup.startRelay': '릴레이 시작',
    'popup.connectSelected': '선택한 AI 연결',
    'popup.stop': '중지',
    'popup.relayLive': '릴레이 진행 중',
    'popup.ready': '준비됨',
    'popup.live': '진행 중',
    'popup.chooseOpenTab': '열린 AI 탭 선택',
    'popup.noSupportedTabs': '지원되는 AI 탭 없음',
    'popup.openTwoTabs': '시작하려면 지원되는 AI 탭을 두 개 이상 여세요.',
    'popup.chooseTwo': '릴레이할 AI 탭 두 개를 선택하세요.',
    'popup.differentTabs': 'AI 1과 AI 2는 서로 다른 탭이어야 합니다.',
    'popup.readyConnect': '선택한 AI를 연결할 준비가 되었습니다.',
    'popup.relayStatus': '릴레이 진행 중 · {count}{suffix}턴 전달됨',
    'popup.starting': '릴레이 시작 중…',
    'popup.unableStart': '릴레이를 시작할 수 없습니다.',
    'popup.relayLiveTurn': '릴레이 진행 중',
    'popup.turnProgress': '턴 {current}{suffix}',
  }),
  en: Object.freeze({
    'language.menu': 'Language',
    'language.ko': '한국어',
    'language.en': 'English',
    'language.ja': '日本語',
    'language.changed': 'Language changed to English.',
    'brand.subtitle': 'Automated AI conversations.',
    'meeting.defaultTitle': 'New AI Meeting',
    'activity.title': 'Activity',
    'aria.meetingTitle': 'Meeting title',
    'aria.savedRoom': 'Saved Room',
    'aria.activePlaybook': 'Active Playbook',
    'aria.sessionTemplate': 'Session template',
    'aria.scheduleMorning': 'Morning scheduled time',
    'aria.scheduleEvening': 'Evening scheduled time',
    'aria.scheduleRunSlot': 'Schedule slot',
    'status.READY': 'READY',
    'status.IDLE': 'IDLE',
    'status.RUNNING': 'RUNNING',
    'status.COMPLETE': 'COMPLETE',
    'status.LIVE': 'LIVE',
    'status.PAUSED': 'PAUSED',
    'status.FINISHED': 'FINISHED',
    'status.NEEDS_ATTENTION': 'NEEDS ATTENTION',
    'workspace.room': 'ROOM',
    'workspace.new': '＋ New',
    'workspace.playbook': 'PLAYBOOK',
    'playbook.freeform': 'Freeform',
    'playbook.channel9': '9-axis Channel Analysis',
    'playbook.debate': 'Debate',
    'playbook.planning': 'Planning Review',
    'playbook.finalSummary': 'Final Summary',
    'participants.label': 'PARTICIPANTS',
    'statusCenter.title': 'Tab Status Center',
    'statusCenter.empty': 'No supported AI tabs are open.',
    'statusCenter.summary': '{ready}/{total} ready',
    'statusCenter.background': 'background',
    'statusCenter.active': 'active tab',
    'statusCenter.tab': 'tab {id}',
    'statusCenter.participant': 'participant {id}',
    'statusCenter.lastSeen': 'checked {time}',
    'statusCenter.transaction': '{stage} · recovery {count}',
    'tab.health.READY': 'READY',
    'tab.health.BUSY': 'BUSY',
    'tab.health.STALE': 'STALE',
    'tab.health.ERROR': 'ERROR',
    'tab.health.DISCONNECTED': 'DISCONNECTED',
    'tab.health.UNBOUND': 'UNBOUND',
    'button.refreshTabs': 'Refresh open AI tabs',
    'button.addAi': 'Add AI',
    'button.retry': 'Retry',
    'button.skip': 'Skip',
    'button.reconnect': 'Reconnect',
    'attention.title': 'Needs attention',
    'attention.message': 'A meeting turn needs recovery.',
    'meeting.label': 'MEETING',
    'turns.zero': '0 turns',
    'turns.one': '1 turn',
    'turns.many': '{count} turns',
    'turn.label': 'Turn {count}',
    'export.transcript': 'Export meeting transcript',
    'export.markdown': 'Download a Markdown transcript',
    'export.json': 'Download a JSON transcript',
    'export.text': 'Download a text transcript',
    'export.reportMarkdown': 'Download the Run report as Markdown',
    'export.reportText': 'Download the Run report as text',
    'empty.title': 'Your meeting room is ready.',
    'empty.description': 'Connect two AI tabs, write a topic, then start the meeting.',
    'mode.group': 'Meeting mode',
    'mode.interactive': 'Interactive',
    'mode.fullAuto': 'Full Auto',
    'mode.interactiveHint': 'Interactive: your messages are added to the room. Use @Gemini or @Copilot to direct a turn.',
    'mode.fullAutoReadyHint': 'Full Auto: AI participants continue without user context.',
    'mode.fullAutoLiveHint': 'Full Auto is observing. AI can hand off with @AI; pause to join.',
    'composer.placeholder': 'Say something to the room…',
    'composer.fullAutoPlaceholder': 'Full Auto is observing…',
    'button.sendToMeeting': 'Send to meeting',
    'button.start': 'Start Meeting',
    'button.resumeMeeting': 'Resume Meeting',
    'button.restartMeeting': 'Restart Meeting',
    'button.pause': 'Pause',
    'button.resume': 'Resume',
    'button.join': 'Join conversation',
    'button.end': 'End',
    'controls.title': 'Meeting Controls',
    'schedule.title': 'Scheduled runs',
    'schedule.enabled': 'Enable scheduled runs',
    'schedule.hint': 'Start the current Room automatically while Chrome is running.',
    'schedule.morning': 'Morning',
    'schedule.evening': 'Evening',
    'schedule.mode': 'Run mode',
    'schedule.topic': 'Scheduled topic',
    'schedule.topicPlaceholder': 'Leave empty to use the current Room topic.',
    'schedule.save': 'Save schedule',
    'schedule.runNow': 'Run now',
    'schedule.none': 'No scheduled run',
    'schedule.next': 'Next: {slot} {time}',
    'schedule.mode.interactive': 'Interactive',
    'schedule.mode.autonomous': 'Full Auto',
    'schedule.enabledShort': 'On',
    'controls.maxAiTurns': 'Maximum AI turns',
    'controls.runTimeLimit': 'Run time limit',
    'controls.runHandoffLimit': 'Run handoff limit',
    'controls.delayBetweenTurns': 'Delay between turns',
    'controls.deliveryRetries': 'Delivery retries',
    'controls.responseTimeout': 'Response timeout',
    'controls.sessionTemplate': 'Session template',
    'controls.smartRouting': 'Smart routing',
    'controls.smartRoutingHint': 'Named AI can speak next',
    'controls.screenshots': 'Screenshots',
    'controls.screenshotsHint': 'Save verified AI replies',
    'controls.loopGuardFullAuto': 'Loop Guard in Full Auto',
    'controls.loopGuardFullAutoHint': 'Pause runaway AI cycles',
    'controls.loopGuardInteractive': 'Loop Guard in Interactive',
    'controls.loopGuardInteractiveHint': 'Optional safety boundary',
    'controls.maxAutonomousHops': 'Maximum autonomous hops',
    'controls.sameParticipantStreak': 'Same participant streak',
    'controls.sameRouteStreak': 'Same route streak',
    'controls.unlimited': '0 = unlimited',
    'controls.disabled': '0 = disabled',
    'controls.min': 'min',
    'controls.sec': 'sec',
    'controls.clearTranscript': 'Clear transcript',
    'controls.newMeeting': 'New meeting',
    'participant.chooseTab': 'Choose an open AI tab…',
    'participant.remove': 'Remove participant',
    'participant.role': 'Role (e.g. Critic)',
    'participant.roleGuidance': 'Role guidance (optional)',
    'participant.slot': 'AI slot {slot}',
    'participant.unbound': 'Unbound AI',
    'session.complete': 'Session complete',
    'session.phase': '{status} · phase {phase}',
    'notice.tabsFound': '{count} supported AI tabs found.',
    'notice.roomLoaded': 'Room loaded.',
    'notice.roomCreated': 'New room created. Connect AI tabs.',
    'notice.playbookUpdated': 'Playbook updated.',
    'notice.newMeeting': 'New meeting created.',
    'notice.reconnectTabs': 'New meeting created. Reconnect participant tabs.',
    'notice.topicAdded': 'Topic added. Press Start Meeting when ready.',
    'notice.fullAutoBlocked': 'Full Auto is observing. Pause to join the conversation.',
    'notice.noTranscript': 'No transcript to export yet.',
    'notice.reportFirst': 'Run a meeting before exporting its report.',
    'notice.saved': 'Saved {filename}.',
    'notice.languageChanged': 'Language changed to {language}.',
    'notice.scheduleSaved': 'Schedule saved.',
    'notice.scheduleStarted': 'Scheduled run started.',
    'notice.scheduleSkipped': 'Scheduled run skipped. Check the open AI tabs and current meeting state.',
    'activity.deliveryConfirmed': 'Delivery confirmed',
    'activity.turn': 'Turn {turn} prepared → {participant} · context {mode}',
    'popup.ai1': 'AI 1',
    'popup.ai2': 'AI 2',
    'popup.chooseAi': 'Choose AI',
    'popup.selectOpenTab': 'Select an open tab',
    'popup.openConversation': 'Open conversation',
    'popup.firstMove': 'FIRST MOVE',
    'popup.whoStarts': 'Who starts?',
    'popup.firstMessageHint': 'AI to receive the first message',
    'popup.startingPrompt': 'STARTING PROMPT',
    'popup.setConversation': 'Set the conversation in motion',
    'popup.seedPlaceholder': 'e.g. Debate each side honestly and ask the other participant one question each turn.',
    'popup.seedNote': 'If empty, start from the first AI’s latest answer.',
    'popup.advanced': 'Advanced settings',
    'popup.advancedHint': 'Turns, delay, screenshots',
    'popup.maxTurns': 'Max turns',
    'popup.delay': 'Delay',
    'popup.saveScreenshots': 'Save response screenshots',
    'popup.screenshotHint': 'Save a PNG when an AI reply finishes',
    'popup.checkingTabs': 'Checking AI tabs…',
    'popup.startRelay': 'START RELAY',
    'popup.connectSelected': 'Connect selected AIs',
    'popup.stop': 'Stop',
    'popup.relayLive': 'RELAY LIVE',
    'popup.ready': 'READY',
    'popup.live': 'LIVE',
    'popup.chooseOpenTab': 'Choose an open AI tab',
    'popup.noSupportedTabs': 'No supported AI tabs open',
    'popup.openTwoTabs': 'Open at least two supported AI tabs to begin.',
    'popup.chooseTwo': 'Choose two AI tabs to create a relay.',
    'popup.differentTabs': 'AI 1 and AI 2 must be different tabs.',
    'popup.readyConnect': 'Ready to connect the selected AIs.',
    'popup.relayStatus': 'Relay live · {count}{suffix} turns delivered',
    'popup.starting': 'Starting relay…',
    'popup.unableStart': 'Unable to start relay.',
    'popup.relayLiveTurn': 'RELAY LIVE',
    'popup.turnProgress': 'Turn {current}{suffix}',
  }),
  ja: Object.freeze({
    'language.menu': '言語',
    'language.ko': '한국어',
    'language.en': 'English',
    'language.ja': '日本語',
    'language.changed': '言語を日本語に変更しました。',
    'brand.subtitle': 'AI会話を自動化します。',
    'meeting.defaultTitle': '新しいAI会議',
    'activity.title': 'アクティビティ',
    'aria.meetingTitle': '会議タイトル',
    'aria.savedRoom': '保存済みルーム',
    'aria.activePlaybook': 'アクティブなプレイブック',
    'aria.sessionTemplate': 'セッションテンプレート',
    'aria.scheduleMorning': '朝の予約時刻',
    'aria.scheduleEvening': '夜の予約時刻',
    'aria.scheduleRunSlot': '予約スロット',
    'status.READY': '準備完了',
    'status.IDLE': '待機中',
    'status.RUNNING': '進行中',
    'status.COMPLETE': '完了',
    'status.LIVE': '実行中',
    'status.PAUSED': '一時停止',
    'status.FINISHED': '完了',
    'status.NEEDS_ATTENTION': '要確認',
    'workspace.room': 'ルーム',
    'workspace.new': '＋ 新規',
    'workspace.playbook': 'プレイブック',
    'playbook.freeform': '自由討論',
    'playbook.channel9': '9軸チャンネル分析',
    'playbook.debate': 'ディベート',
    'playbook.planning': '企画レビュー',
    'playbook.finalSummary': '最終要約',
    'participants.label': '参加者',
    'statusCenter.title': 'AIタブ状態センター',
    'statusCenter.empty': '対応するAIタブが開いていません。',
    'statusCenter.summary': '{ready}/{total} 準備完了',
    'statusCenter.background': 'バックグラウンド',
    'statusCenter.active': 'アクティブタブ',
    'statusCenter.tab': 'タブ {id}',
    'statusCenter.participant': '参加者 {id}',
    'statusCenter.lastSeen': '確認 {time}',
    'statusCenter.transaction': '{stage} · 復旧 {count}',
    'tab.health.READY': '正常',
    'tab.health.BUSY': '処理中',
    'tab.health.STALE': '古い状態',
    'tab.health.ERROR': 'エラー',
    'tab.health.DISCONNECTED': '未接続',
    'tab.health.UNBOUND': '割り当てなし',
    'button.refreshTabs': '開いているAIタブを更新',
    'button.addAi': 'AIを追加',
    'button.retry': '再試行',
    'button.skip': 'スキップ',
    'button.reconnect': '再接続',
    'attention.title': '確認が必要です',
    'attention.message': '会議ターンの復旧が必要です。',
    'meeting.label': '会議',
    'turns.zero': '0ターン',
    'turns.one': '1ターン',
    'turns.many': '{count}ターン',
    'turn.label': '{count}ターン目',
    'export.transcript': '会議記録をエクスポート',
    'export.markdown': 'Markdown記録をダウンロード',
    'export.json': 'JSON記録をダウンロード',
    'export.text': 'テキスト記録をダウンロード',
    'export.reportMarkdown': '実行レポートをMarkdownでダウンロード',
    'export.reportText': '実行レポートをテキストでダウンロード',
    'empty.title': '会議室の準備ができました。',
    'empty.description': 'AIタブを2つ接続し、テーマを入力して会議を開始してください。',
    'mode.group': '会議モード',
    'mode.interactive': '対話型',
    'mode.fullAuto': 'フルオート',
    'mode.interactiveHint': '対話型：ユーザーのメッセージをルームに追加します。@Gemini や @Copilot でターンを指定できます。',
    'mode.fullAutoReadyHint': 'フルオート：AI参加者がユーザーの文脈なしで会話を続けます。',
    'mode.fullAutoLiveHint': 'フルオートが観察中です。@AIで引き継げます。参加するには一時停止してください。',
    'composer.placeholder': '会議室に話しかける…',
    'composer.fullAutoPlaceholder': 'フルオートが観察中…',
    'button.sendToMeeting': '会議に送信',
    'button.start': '会議を開始',
    'button.resumeMeeting': '会議を再開',
    'button.restartMeeting': '会議を再スタート',
    'button.pause': '一時停止',
    'button.resume': '再開',
    'button.join': '会話に参加',
    'button.end': '終了',
    'controls.title': '会議コントロール',
    'schedule.title': '予約実行',
    'schedule.enabled': '予約自動実行',
    'schedule.hint': 'Chromeの実行中に現在のRoomを自動開始します。',
    'schedule.morning': '朝',
    'schedule.evening': '夜',
    'schedule.mode': '実行モード',
    'schedule.topic': '予約トピック',
    'schedule.topicPlaceholder': '空欄なら現在のRoomのトピックを使います。',
    'schedule.save': '予約を保存',
    'schedule.runNow': '今すぐ実行',
    'schedule.none': '予約なし',
    'schedule.next': '次回: {slot} {time}',
    'schedule.mode.interactive': '対話型',
    'schedule.mode.autonomous': 'Full Auto',
    'schedule.enabledShort': '有効',
    'controls.maxAiTurns': 'AIの最大ターン数',
    'controls.runTimeLimit': '実行時間制限',
    'controls.runHandoffLimit': '実行引き継ぎ上限',
    'controls.delayBetweenTurns': 'ターン間の遅延',
    'controls.deliveryRetries': '送信リトライ',
    'controls.responseTimeout': '応答タイムアウト',
    'controls.sessionTemplate': 'セッションテンプレート',
    'controls.smartRouting': 'スマートルーティング',
    'controls.smartRoutingHint': '名前を指定されたAIが次に話せます',
    'controls.screenshots': 'スクリーンショット',
    'controls.screenshotsHint': '確認済みのAI回答を保存',
    'controls.loopGuardFullAuto': 'フルオートのLoop Guard',
    'controls.loopGuardFullAutoHint': '暴走するAIサイクルを一時停止',
    'controls.loopGuardInteractive': '対話型のLoop Guard',
    'controls.loopGuardInteractiveHint': '任意の安全境界',
    'controls.maxAutonomousHops': '自動引き継ぎの最大数',
    'controls.sameParticipantStreak': '同じ参加者の連続回数',
    'controls.sameRouteStreak': '同じルートの連続回数',
    'controls.unlimited': '0 = 無制限',
    'controls.disabled': '0 = 無効',
    'controls.min': '分',
    'controls.sec': '秒',
    'controls.clearTranscript': '会議記録を消去',
    'controls.newMeeting': '新しい会議',
    'participant.chooseTab': '開いているAIタブを選択…',
    'participant.remove': '参加者を削除',
    'participant.role': '役割（例：批評家）',
    'participant.roleGuidance': '役割ガイダンス（任意）',
    'participant.slot': 'AIスロット {slot}',
    'participant.unbound': '未接続のAI',
    'session.complete': 'セッション完了',
    'session.phase': '{status} · {phase}段階',
    'notice.tabsFound': '対応するAIタブを{count}個見つけました。',
    'notice.roomLoaded': 'ルームを読み込みました。',
    'notice.roomCreated': '新しいルームを作成しました。AIタブを接続してください。',
    'notice.playbookUpdated': 'プレイブックを更新しました。',
    'notice.newMeeting': '新しい会議を作成しました。',
    'notice.reconnectTabs': '新しい会議を作成しました。参加者タブを再接続してください。',
    'notice.topicAdded': 'テーマを追加しました。準備ができたら会議を開始してください。',
    'notice.fullAutoBlocked': 'フルオートが観察中です。会話に参加するには一時停止してください。',
    'notice.noTranscript': 'エクスポートする会議記録がありません。',
    'notice.reportFirst': 'レポートをエクスポートする前に会議を実行してください。',
    'notice.saved': '{filename}を保存しました。',
    'notice.languageChanged': '言語を{language}に変更しました。',
    'notice.scheduleSaved': '予約を保存しました。',
    'notice.scheduleStarted': '予約実行を開始しました。',
    'notice.scheduleSkipped': '予約実行をスキップしました。開いているAIタブと会議状態を確認してください。',
    'activity.deliveryConfirmed': '送信を確認',
    'activity.turn': '{turn}ターン目を準備 → {participant} · コンテキスト {mode}',
    'popup.ai1': 'AI 1',
    'popup.ai2': 'AI 2',
    'popup.chooseAi': 'AIを選択',
    'popup.selectOpenTab': '開いているタブを選択',
    'popup.openConversation': '開いている会話',
    'popup.firstMove': '最初の一手',
    'popup.whoStarts': '誰から始めますか？',
    'popup.firstMessageHint': '最初のメッセージを受け取るAI',
    'popup.startingPrompt': '開始プロンプト',
    'popup.setConversation': '会話を始める',
    'popup.seedPlaceholder': '例：双方の長所と短所を率直に議論し、各ターンで相手に質問を1つしてください。',
    'popup.seedNote': '空欄の場合、最初のAIの最新回答から開始します。',
    'popup.advanced': '詳細設定',
    'popup.advancedHint': 'ターン、遅延、スクリーンショット',
    'popup.maxTurns': '最大ターン数',
    'popup.delay': '遅延',
    'popup.saveScreenshots': '回答のスクリーンショットを保存',
    'popup.screenshotHint': 'AI回答の完了時にPNGで保存',
    'popup.checkingTabs': 'AIタブを確認中…',
    'popup.startRelay': 'リレーを開始',
    'popup.connectSelected': '選択したAIを接続',
    'popup.stop': '停止',
    'popup.relayLive': 'リレー実行中',
    'popup.ready': '準備完了',
    'popup.live': '実行中',
    'popup.chooseOpenTab': '開いているAIタブを選択',
    'popup.noSupportedTabs': '対応するAIタブがありません',
    'popup.openTwoTabs': '開始するには対応するAIタブを2つ以上開いてください。',
    'popup.chooseTwo': 'リレーするAIタブを2つ選択してください。',
    'popup.differentTabs': 'AI 1とAI 2は別のタブにしてください。',
    'popup.readyConnect': '選択したAIを接続する準備ができました。',
    'popup.relayStatus': 'リレー実行中 · {count}{suffix}ターン送信済み',
    'popup.starting': 'リレーを開始中…',
    'popup.unableStart': 'リレーを開始できません。',
    'popup.relayLiveTurn': 'リレー実行中',
    'popup.turnProgress': '{current}{suffix}ターン',
  }),
});

const SESSION_PHASE_MESSAGES = Object.freeze({
  ko: Object.freeze({
    discussion: Object.freeze({ name: '자유 토론', instruction: '주제를 자연스럽게 토론하고 최신 AI 발언을 발전시키세요.' }),
    'axis-1': Object.freeze({ name: '콘셉트', instruction: '채널 아이디어, 약속, 대상 시청자, 독자적 관점을 평가하세요. 근거, 위험, 테스트할 개선안 하나를 제시하세요.' }),
    'axis-2': Object.freeze({ name: '내레이션', instruction: '내러티브 구조, 속도, 긴장감, 명확성을 평가하세요. 근거, 위험, 테스트할 개선안 하나를 제시하세요.' }),
    'axis-3': Object.freeze({ name: '시각적 리듬', instruction: '시각적 호흡, 패턴 변화, 구도, 주의 흐름을 평가하세요. 근거, 위험, 테스트할 개선안 하나를 제시하세요.' }),
    'axis-4': Object.freeze({ name: '메시지 압축', instruction: '메시지를 압축했을 때 의미가 얼마나 유지되는지 평가하세요. 근거, 위험, 테스트할 개선안 하나를 제시하세요.' }),
    'axis-5': Object.freeze({ name: '브랜드 시그니처', instruction: '알아볼 수 있는 목소리, 반복 장치, 정체성을 평가하세요. 근거, 위험, 테스트할 개선안 하나를 제시하세요.' }),
    'axis-6': Object.freeze({ name: '패키징', instruction: '제목, 썸네일, 첫 약속, 클릭할 이유를 평가하세요. 근거, 위험, 테스트할 개선안 하나를 제시하세요.' }),
    'axis-7': Object.freeze({ name: '리텐션', instruction: '초반 이탈 위험, 보상 시점, 다시 찾을 이유를 평가하세요. 근거, 위험, 테스트할 개선안 하나를 제시하세요.' }),
    'axis-8': Object.freeze({ name: '반복 가능성', instruction: '같은 형식으로 강한 에피소드 50~100편을 만들 수 있는지 평가하세요. 근거, 위험, 테스트할 개선안 하나를 제시하세요.' }),
    'axis-9': Object.freeze({ name: '배포', instruction: '검색, 추천, Shorts, 외부 공유, 성장 루프를 평가하세요. 근거, 위험, 테스트할 개선안 하나를 제시하세요.' }),
    framing: Object.freeze({ name: '논점 정리', instruction: '논쟁하기 전에 결정할 문제, 용어, 가정, 성공 기준을 정의하세요.' }),
    arguments: Object.freeze({ name: '주장', instruction: '찬반 양쪽에서 가장 강하고 근거가 있는 주장을 제시하세요.' }),
    rebuttals: Object.freeze({ name: '반박', instruction: '약한 가정에 도전하고 가장 강한 반대 주장에 직접 답하세요.' }),
    synthesis: Object.freeze({ name: '종합', instruction: '논쟁을 명확한 권고, 상충관계, 미해결 질문으로 종합하세요.' }),
    objective: Object.freeze({ name: '목표', instruction: '원하는 결과와 측정 방법을 정의하세요.' }),
    constraints: Object.freeze({ name: '제약 조건', instruction: '제약, 의존성, 위험, 양보할 수 없는 요구사항을 나열하세요.' }),
    options: Object.freeze({ name: '선택지', instruction: '명확한 상충관계와 함께 실행 가능한 선택지를 만들고 비교하세요.' }),
    decision: Object.freeze({ name: '결정', instruction: '가장 강한 선택지를 고르고 다른 선택지를 거부한 이유를 설명하세요.' }),
    'next-actions': Object.freeze({ name: '다음 행동', instruction: '결정을 담당자 또는 확인 지점이 있는 순서화된 검증 가능한 행동으로 바꾸세요.' }),
    summary: Object.freeze({ name: '최종 요약', instruction: '대화, 결정, 열린 질문, 구체적인 다음 행동을 요약하세요.' }),
  }),
  ja: Object.freeze({
    discussion: Object.freeze({ name: '自由討論', instruction: 'テーマを自然に議論し、最新のAI発言を発展させてください。' }),
    'axis-1': Object.freeze({ name: 'コンセプト', instruction: 'チャンネルのアイデア、約束、対象視聴者、独自の視点を評価してください。根拠、リスク、試す改善案を1つ示してください。' }),
    'axis-2': Object.freeze({ name: 'ナレーション', instruction: '物語構成、テンポ、緊張感、明確さを評価してください。根拠、リスク、試す改善案を1つ示してください。' }),
    'axis-3': Object.freeze({ name: 'ビジュアルリズム', instruction: '映像のテンポ、パターンの変化、構図、注意の流れを評価してください。根拠、リスク、試す改善案を1つ示してください。' }),
    'axis-4': Object.freeze({ name: 'メッセージ圧縮', instruction: 'メッセージを短くしたとき、どれだけ意味が残るかを評価してください。根拠、リスク、試す改善案を1つ示してください。' }),
    'axis-5': Object.freeze({ name: 'ブランドシグネチャ', instruction: '認識できる声、反復する仕掛け、アイデンティティを評価してください。根拠、リスク、試す改善案を1つ示してください。' }),
    'axis-6': Object.freeze({ name: 'パッケージング', instruction: 'タイトル、サムネイル、冒頭の約束、クリックする理由を評価してください。根拠、リスク、試す改善案を1つ示してください。' }),
    'axis-7': Object.freeze({ name: 'リテンション', instruction: '序盤の離脱リスク、見返りのタイミング、再訪する理由を評価してください。根拠、リスク、試す改善案を1つ示してください。' }),
    'axis-8': Object.freeze({ name: '反復可能性', instruction: '同じ形式で強いエピソードを50〜100本作れるか評価してください。根拠、リスク、試す改善案を1つ示してください。' }),
    'axis-9': Object.freeze({ name: '配信', instruction: '検索、推薦、Shorts、外部共有、成長ループを評価してください。根拠、リスク、試す改善案を1つ示してください。' }),
    framing: Object.freeze({ name: '論点整理', instruction: '議論する前に、決めること、用語、前提、成功基準を定義してください。' }),
    arguments: Object.freeze({ name: '主張', instruction: '賛成・反対の両方について、最も強く根拠のある主張を示してください。' }),
    rebuttals: Object.freeze({ name: '反論', instruction: '弱い前提に問いを投げ、最も強い反対意見に直接答えてください。' }),
    synthesis: Object.freeze({ name: '統合', instruction: '議論を明確な推奨、トレードオフ、未解決の問いにまとめてください。' }),
    objective: Object.freeze({ name: '目的', instruction: '望む成果と、その測定方法を定義してください。' }),
    constraints: Object.freeze({ name: '制約', instruction: '制約、依存関係、リスク、譲れない要件を列挙してください。' }),
    options: Object.freeze({ name: '選択肢', instruction: '明確なトレードオフを示し、実行可能な選択肢を作って比較してください。' }),
    decision: Object.freeze({ name: '決定', instruction: '最も強い選択肢を選び、他の選択肢を退けた理由を説明してください。' }),
    'next-actions': Object.freeze({ name: '次のアクション', instruction: '決定を、担当者または確認点を含む順序付きの検証可能な行動に変えてください。' }),
    summary: Object.freeze({ name: '最終要約', instruction: '会話、決定、未解決の問い、具体的な次のアクションを要約してください。' }),
  }),
});

export function normalizeLanguage(value) {
  return Object.hasOwn(SUPPORTED_LANGUAGES, value) ? value : DEFAULT_LANGUAGE;
}

export function languageInfo(value) {
  return SUPPORTED_LANGUAGES[normalizeLanguage(value)];
}

export function languageInstruction(value) {
  return languageInfo(value).instruction;
}

export function localizedSessionPhase(language, phase = {}) {
  const normalized = normalizeLanguage(language);
  const localized = SESSION_PHASE_MESSAGES[normalized]?.[phase?.id];
  if (!localized) return { ...phase };
  return { ...phase, name: localized.name, instruction: localized.instruction };
}

export function promptText(language, key, variables = {}) {
  const normalized = normalizeLanguage(language);
  const template = PROMPT_MESSAGES[normalized]?.[key] ?? PROMPT_MESSAGES.en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (_match, name) => String(variables[name] ?? `{${name}}`));
}

export function translate(language, key, variables = {}) {
  const normalized = normalizeLanguage(language);
  const template = MESSAGES[normalized]?.[key] ?? MESSAGES.en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (_match, name) => String(variables[name] ?? `{${name}}`));
}

export function languageOptions() {
  return Object.values(SUPPORTED_LANGUAGES).map(({ code, label }) => ({ code, label }));
}
